# https://docs.travis-ci.com/user/languages/r
language: r
# dist: trusty
# trusty will only work with sudo: true for now
# https://ropensci.org/blog/2016/07/12/travis-osx
sudo: false
cache: packages

addons:
  apt:
    packages:
     - r-cran-rodbc

r:
  - oldrel # when oldrel = 3.1, there are S3 method problems I can't debug
  - release
  - devel

matrix:
  allow_failures:
  - r: oldrel

repos:
  CRAN: https://cloud.r-project.org

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

warnings_are_errors: true

before_script:
  - sed -i.old '/[Dd]ata/d' .Rbuildignore # do include data for testing
  - export R_CHECK_CRAN_INCOMING_=FALSE
  - export _R_CHECK_FORCE_SUGGESTS_=FALSE
  - rm -rf data.old .Rinstignore .Rbuildignore  # do install everything for testing

after_success:
 - Rscript -e 'covr::coveralls()'
 - Rscript -e 'lintr::lint_package()'

notifications:
  email:
  on_success: change
  on_failure: change

on_failure:
  - ./travis-tool.sh dump_logs
